version: '3.1'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
  db:
    container_name: "dybi-pg"
    image: postgres:12.4-alpine
    volumes:
      - "./postgres-data:/var/lib/postgresql/data:rw"
    ports:
      - "${PG_PORT}:5432"
    environment:
      POSTGRES_DB: "${PG_DATABASE}"
      POSTGRES_USER: "${PG_USERNAME}"
      POSTGRES_PASSWORD: "${$PG_PASSWORD}"
    restart: unless-stopped

  pg-admin:
    image: "dpage/pgadmin4"
    container_name: "dybi-pg-admin"
    restart: always
    ports:
      - "${PGADMIN_PORT}": 80
    environment:
      PGADMIN_DEFAULT_EMAIL: "github@igorilic.net"
      PGADMIN_DEFAULT_PASSWORD: "${PG_PASSWORD}"
