version: '3.1'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
  db:
    container_name: "dybi-pg"
    image: postgres:12.4-alpine
    volumes:
      - "./postgres-data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "dybi"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    restart: unless-stopped

  pg-admin:
    image: "dpage/pgadmin4"
    container_name: "dybi-pg-admin"
    restart: always
    ports:
      - 8088:80
    environment:
      PGADMIN_DEFAULT_EMAIL: "github@igorilic.net"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
